### ISSUE TITLE
Components/GUISkin.py:45 createGUIScreen warning, skin is missing element key_info in <class 'Screens.About.About'>

### ISSUE THREAD

**Issue by Sign-in-and** [littlesat/skin-PLiHD#642]
15:53:27.6130 {   } skin.py:1067 readSkin [Skin] Processing screen: About
15:53:27.6180 { E } skin.py:1072 readSkin [Skin] Error in About: 'Button' object has no attribute 'downstream_elements'
15:53:27.6201 { W } Components/GUISkin.py:45 createGUIScreen warning, skin is missing element key_info in <class 'Screens.About.About'>
15:53:27.6210 { W } Components/GUISkin.py:45 createGUIScreen warning, skin is missing element AboutScrollLabel in <class 'Screens.About.About'>
15:53:27.6261 {   } skin.py:1067 readSkin [Skin] Processing screen: SimpleSummary
15:53:27.6270 {   } Screens/Screen.py:146 show [SCREENNAME]  ['About_summary', 'SimpleSummary']
15:53:27.6276 {   } Screens/Screen.py:146 show [SCREENNAME]  About
![empty](https://user-images.githubusercontent.com/36300999/39366146-66f98ea4-4a33-11e8-80ca-dad826508769.PNG)

**Comment by Sign-in-and** [comment]
Error in About: 'Button' object has no attribute 'downstream_elements'

**Comment by ims21** [comment]
Our original skin and original enigma code displaying there in screen title "Über" only - without "boxname". It seems, you are using modified code or skin -> look and ask help there, where it was modified, pls...

**Comment by Sign-in-and** [comment]
The skin is not modified and every other skin works with About
